spring:
  profiles:
    active: dev
  application:
    name: face_recognition_auth_server
  cloud:
    config:
      uri: http://localhost:8181
      username: config
      password: configserver123
  config:
    import: configserver:http://localhost:8181

front-end-url: ${FRONT_END_URL_PREFIX}